Escape `loadBalancerSourceRanges` in rendered template (#172)
Since the spec want's this as an array (not a single string, though that
work in a pinch) we use the `toJson` filter to make this valid YAML
(JSON being a enough of a subset of YAML).

Previously, if we put this in our values file:

    nginx:
      loadBalancerSourceRanges:
        - 10.1.0.0/16
        - 10.2.0.0/16

we would get this kind of error:

> Error: Service "knobby-toucan-nginx" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[10.1.0.0/16 10.2.0.0/16]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24

With this change the firewall rules are updated with the two IP ranges
provided.